name: Monthly API Check and Release

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Curl current data
        run: |
          curl -o current_data.json https://winston.emtech.cc/api/list
      - name: get the latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          latest_release=$(gh release list --json name --limit 1 | jq -r '.[] | .name')
          echo "Latest release: $latest_release"

          # Download the latest release asset
          gh release download "$latest_release" -p "*.json" -O latest_json.json --clobber || {
            echo "Failed to download latest release asset"
            exit 1
          }
      - name: Compare current data with latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          if [ -f current_data.json ]; then
            # Sort and normalize both JSON files to ensure consistent comparison
            jq -S '.' current_data.json > current_sorted.json
            jq -S '.' latest_json.json > latest_sorted.json
            
            if ! cmp -s current_sorted.json latest_sorted.json; then
              echo "Changes detected between current data and the latest release."
              gh release create v$(date +%Y-%m-%d) current_data.json --title "API Update $(date +%Y-%m-%d)" --notes "Automated API data update for $(date +%Y-%m-%d)"
            else
              echo "Current data matches the latest release exactly."
            fi
            
            # Clean up temporary files
            rm current_sorted.json latest_sorted.json
          else
            echo "current_data.json does not exist."
            exit 1
          fi
